dist: trusty
language: cpp

cache: ccache

os:
  - linux
  - osx
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - cmake
    - ccache
    

install:
   - bash build_occt.sh
   
build:

    
    
  
