init:
  - git config --global core.autocrlf input

version: '7.1.{build}'

clone_depth: 5

install:
  - cmd: build_occt.bat

build_script:
  -  echo This is my custom build script
# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script
test: off
build: off  
deploy: off

