init:
  - git config --global core.autocrlf input

version: '7.1.{build}'

clone_depth: 5

install:
  - cmd: build_occt.bat
  - cmd: ECHO %FULL_ARCHIVE%  

build_script:
  -  echo This is my custom build script
# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script
test: off
build: off
deploy: 
  # release: myproduct-v$(appveyor_build_version)
  # description: 'Release description'
  provider: GitHub
  auth_token:
    secure: ByhARJzBLendy3Ys8MK+xbPv+aP39Pixz5OhDsw1ztdNUsRXmvGtPpcS697hIMlI # my encrypted token from GitHub
  artifact: $(FULL_ARCHIVE)
  draft:      true
  prerelease: true
  force_update: true
  on:
    # branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

# https://www.appveyor.com/docs/deployment/github/
