image: Visual Studio 2017
init:
  - git config --global core.autocrlf input

version: '7.2.{build}'

clone_depth: 5

install:
  - cmd: build_occt.bat
  - cmd: ECHO %FULL_ARCHIVE%  

build_script:
  -  echo This is my custom build script
# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script
test: off
build: off

artifacts:
  path: '**\*.zip' ## find all zip file recursively
  name: OCCT

deploy: 
  # release: myproduct-v$(appveyor_build_version)
  # description: 'Release description'
  provider: GitHub
  auth_token:
    secure: pEyC6k67/FGhaa9ePlUbbeIKi2H4XlrtCoaLrv03Z9OonEiXz4vH0/3ULzdB/qQB
  artifact: OCCT
  draft:      true
  prerelease: true
  force_update: true
  on:
    # branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

# https://www.appveyor.com/docs/deployment/github/
